Added code for multiple locales
The locale setting is renamed to locales and can hold a space delimited
list of locales that are to be enabled on the installed system.
All listed (valid) locales will be generated during installation

diff --git a/scripts/etc/init.d/rcS b/scripts/etc/init.d/rcS
--- a/scripts/etc/init.d/rcS
+++ b/scripts/etc/init.d/rcS
@@ -15,7 +15,7 @@ bootsize=+50M
 rootsize=
 timeserver=time.nist.gov
 timezone=Etc/UTC
-locale=
+locales=
 ip_addr=dhcp
 ip_netmask=0.0.0.0
 ip_broadcast=0.0.0.0
@@ -354,7 +354,7 @@ echo "  bootsize = $bootsize"
 echo "  rootsize = $rootsize"
 echo "  timeserver = $timeserver"
 echo "  timezone = $timezone"
-echo "  locale = $locale"
+echo "  locales = $locales"
 echo "  cmdline = $cmdline"
 echo "  usbroot = $usbroot"
 echo "  rootdev = $rootdev"
@@ -539,15 +539,20 @@ else
     echo "FAILED !"
 fi
 
-# set locale and generate locale data
-if [ "$locale" != "" ] ; then
-    echo -n "  Configuring locale... "
-    sed -i "s/^# \($locale.*\)/\1/" /rootfs/etc/locale.gen
-    chroot /rootfs /usr/sbin/locale-gen &> /dev/null
-    if [ $? -eq 0 ]; then
-        echo "OK"
-    else
-        echo "FAILED !"
+# generate locale data
+if [ ! -z "$locales" ]; then
+    echo -n "  Enabling locales... "
+    for locale in $locales; do
+        if [ $(grep -c $locale /etc/locale.gen) -gt 0 ]; then
+            sed -i "s/^# \($locale.*\)/\1/" /rootfs/etc/locale.gen
+        else
+            echo -n "$locale NOT found... "
+        fi
+    done
+    echo
+    chroot /rootfs /usr/sbin/locale-gen | sed 's/^/  /'
+    if [ $? -ne 0 ]; then
+        echo "  ERROR while generating locales!!"
     fi
 fi
 
