Added the system_default_locale setting
If the system_default_locale value is set, the value is passed to
update-locale, which in turn does the system specific setup so the
locale is used as a system default
(writes LANG=<locale> to /etc/default/locale)

diff --git a/scripts/etc/init.d/rcS b/scripts/etc/init.d/rcS
--- a/scripts/etc/init.d/rcS
+++ b/scripts/etc/init.d/rcS
@@ -16,6 +16,7 @@ rootsize=
 timeserver=time.nist.gov
 timezone=Etc/UTC
 locales=
+system_default_locale=
 ip_addr=dhcp
 ip_netmask=0.0.0.0
 ip_broadcast=0.0.0.0
@@ -355,6 +356,7 @@ echo "  rootsize = $rootsize"
 echo "  timeserver = $timeserver"
 echo "  timezone = $timezone"
 echo "  locales = $locales"
+echo "  system_default_locale = $system_default_locale"
 echo "  cmdline = $cmdline"
 echo "  usbroot = $usbroot"
 echo "  rootdev = $rootdev"
@@ -552,7 +554,18 @@ if [ ! -z "$locales" ]; then
     echo
     chroot /rootfs /usr/sbin/locale-gen | sed 's/^/  /'
     if [ $? -ne 0 ]; then
-        echo "  ERROR while generating locales!!"
+        echo "  ERROR while generating locales !"
+    fi
+fi
+
+# set system default locale
+if [ ! -z "$system_default_locale" ]; then
+    echo -n "  Setting system default locale... "
+    chroot /rootfs /usr/sbin/update-locale LANG="$system_default_locale" &> /dev/null
+    if [ $? -eq 0 ]; then
+        echo "OK"
+    else
+        echo "FAILED !"
     fi
 fi
 
