modprobe the `bcm2708-rng` module ASAP

diff --git a/scripts/etc/init.d/rcS b/scripts/etc/init.d/rcS
--- a/scripts/etc/init.d/rcS
+++ b/scripts/etc/init.d/rcS
@@ -141,6 +141,14 @@ cp -r /boot/* /bootfs/ || fail
 umount /boot || fail
 echo "OK"
 
+echo -n "Starting HWRNG "
+modprobe bcm2708-rng
+if [ $? -eq 0 ]; then
+  echo "succeeded!"
+else
+  echo "FAILED!"
+fi
+
 if [ -e /bootfs/installer-config.txt ]; then
     echo "================================================="
     echo "=== Start executing installer-config.txt. ==="
