Added support for setting timezone
A setting named timezone can be added to installer-config.txt which
will set the timezone of the installed system. The value (default is
Etc/UTC) must be a valid timezone identifier (e.g. Europe/Ljubljana)

diff --git a/scripts/etc/init.d/rcS b/scripts/etc/init.d/rcS
--- a/scripts/etc/init.d/rcS
+++ b/scripts/etc/init.d/rcS
@@ -14,6 +14,7 @@ cdebootstrap_cmdline=
 bootsize=+50M
 rootsize=
 timeserver=time.nist.gov
+timezone=Etc/UTC
 ip_addr=dhcp
 ip_netmask=0.0.0.0
 ip_broadcast=0.0.0.0
@@ -347,6 +348,7 @@ echo "  cdebootstrap_cmdline = $cdebootstrap_cmdline"
 echo "  bootsize = $bootsize"
 echo "  rootsize = $rootsize"
 echo "  timeserver = $timeserver"
+echo "  timezone = $timezone"
 echo "  cmdline = $cmdline"
 echo "  usbroot = $usbroot"
 echo "  rootdev = $rootdev"
@@ -520,6 +522,16 @@ echo -n "  Enabling serial console... "
 echo "#Spawn a getty on Raspberry Pi serial line" >> /rootfs/etc/inittab
 echo "T0:23:respawn:/sbin/getty -L ttyAMA0 115200 vt100" >> /rootfs/etc/inittab
 echo "OK"
+
+# set timezone and reconfigure tzdata package
+echo -n "  Configuring tzdata, setting timezone to $timezone... "
+echo "$timezone" > /rootfs/etc/timezone
+chroot /rootfs /usr/sbin/dpkg-reconfigure -f noninteractive tzdata &> /dev/null
+if [ $? -eq 0 ]; then
+    echo "OK"
+else
+    echo "FAILED !"
+fi
 
 # openssh-server in jessie doesn't allow root to login using password anymore
 # this hack does allow it (until a proper solution is implemented)
