Added configuration for installing over wifi User must add wpa_supplicant.conf file to /boot/config/ which is in wpa_supplicant-format, see man wpa_supplicant.conf.
Added following options and added it to readme
ifname - interface name used for network connection
wlandriver - filename of driver which is inserted into the kernel. This file must exist in the default installation.

Installation now includes wpa_supplicant and firmware-realtek package.
Directory /drivers/wireless holds wlan drivers

diff --git a/scripts/etc/init.d/rcS b/scripts/etc/init.d/rcS
--- a/scripts/etc/init.d/rcS
+++ b/scripts/etc/init.d/rcS
@@ -23,11 +23,13 @@ timeserver=time.nist.gov
 timezone=Etc/UTC
 locales=
 system_default_locale=
+ifname=eth0
 ip_addr=dhcp
 ip_netmask=0.0.0.0
 ip_broadcast=0.0.0.0
 ip_gateway=0.0.0.0
 ip_nameservers=
+wlandriver=
 online_config=
 usbroot=
 cmdline="dwc_otg.lpm_enable=0 console=ttyAMA0,115200 kgdboc=ttyAMA0,115200 console=tty1 elevator=deadline"
@@ -163,6 +165,10 @@ if [ -e /bootfs/installer-config.txt ]; then
     echo "================================================="
 fi
 
+if [ -e /bootfs/config/wpa_supplicant.conf ]; then
+    sanitize_inputfile /bootfs/config/wpa_supplicant.conf
+fi
+
 case "$rootfstype" in
   "btrfs")
     kernel_module=true
@@ -198,11 +204,20 @@ fi
 echo "  online_config = $online_config"
 echo
 
-echo -n "Waiting for eth0... "
+echo "Waiting for $ifname... "
+
+if [ "$ifname" != "eth0" ]; then
+    # if eth0 is not the chosen eth interface it is a wireless interface and a driver must be loaded
+    echo -n "Loding driver $wlandriver... "
+    insmod /drivers/wireless/$wlandriver || fail
+    [ $? -eq 0 ] && echo "OK"
+    # Also, replace eth0 as udhcpc dns interface
+    sed -i "s/PEERDNS_IF=.*/PEERDNS_IF=$ifname/g" /etc/udhcpc/default.script
+fi
 
 for i in `seq 1 10`; do
 
-    ifconfig eth0 &>/dev/null
+    ifconfig $ifname &>/dev/null
     if [ $? -eq 0 ]; then
         break
     fi
@@ -217,19 +232,26 @@ for i in `seq 1 10`; do
     echo -n "$i.. "
 done
 
-if [ "$ip_addr" = "dhcp" ]; then
-    echo -n "Configuring eth0 with DHCP... "
+if [ "$ifname" != "eth0" ]; then
+    # if eth0 is not the chosen eth interface it is a wireless interface and wpa_supplicant must connect to wlan
+    echo -n "Running wpa_supplicant... "
+    wpa_supplicant -B -Dwext -c/bootfs/config/wpa_supplicant.conf -iwlan0 >& /dev/null || fail
+    [ $? -eq 0 ] && echo "OK"
+fi
 
-    udhcpc -i eth0 &>/dev/null
+if [ "$ip_addr" = "dhcp" ]; then
+    echo -n "Configuring $ifname with DHCP... "
+
+    udhcpc -i $ifname &>/dev/null
     if [ $? -eq 0 ]; then
-        ifconfig eth0 | fgrep addr: | awk '{print $2}' | cut -d: -f2
+        ifconfig $ifname | fgrep addr: | awk '{print $2}' | cut -d: -f2
     else
         echo "FAILED"
         fail
     fi
 else
-    echo -n "Configuring eth0 with static ip $ip_addr... "
-    ifconfig eth0 up inet $ip_addr netmask $ip_netmask broadcast $ip_broadcast || fail
+    echo -n "Configuring $ifname with static ip $ip_addr... "
+    ifconfig $ifname up inet $ip_addr netmask $ip_netmask broadcast $ip_broadcast || fail
     route add default gw $ip_gateway || fail
     echo -n > /etc/resolv.conf
     for i in $ip_nameservers; do
@@ -601,17 +623,20 @@ echo "iface lo inet loopback" >> /rootfs/etc/network/interfaces || fail
 echo "" >>  /rootfs/etc/network/interfaces || fail
 
 # eth0 config
-echo "auto eth0" >> /rootfs/etc/network/interfaces || fail
+echo "auto $ifname" >> /rootfs/etc/network/interfaces || fail
 if [ "$ip_addr" = "dhcp" ]; then
-    echo "iface eth0 inet dhcp" >> /rootfs/etc/network/interfaces || fail
+    echo "iface $ifname inet dhcp" >> /rootfs/etc/network/interfaces || fail
 else
-    echo "iface eth0 inet static" >> /rootfs/etc/network/interfaces || fail
+    echo "iface $ifname inet static" >> /rootfs/etc/network/interfaces || fail
     echo "    address $ip_addr" >> /rootfs/etc/network/interfaces || fail
     echo "    netmask $ip_netmask" >> /rootfs/etc/network/interfaces || fail
     echo "    broadcast $ip_broadcast" >> /rootfs/etc/network/interfaces || fail
     echo "    gateway $ip_gateway" >> /rootfs/etc/network/interfaces || fail
 
     cp /etc/resolv.conf /rootfs/etc/ || fail
+fi
+if [ "$ifname" != "eth0" ]; then
+    echo "wpa-conf /boot/config/wpa_supplicant.conf" >> /rootfs/etc/network/interfaces || fail
 fi
 echo "OK"
 
@@ -786,6 +811,18 @@ if [ $? -eq 0 ]; then
     echo "OK"
 else
     echo "FAILED !"
+fi
+
+# if eth0 was not used during initial boot, a wireless interfaces was used
+if [ "$ifname" != "eth0" ]; then
+    # Install wireless dependencies
+    echo -n "Installing wpasupplicant package... "
+    chroot /rootfs /usr/bin/apt-get -y install wpasupplicant firmware-realtek >& /dev/null
+    if [ $? -eq 0 ]; then
+        echo "OK"
+    else
+        echo "FAILED !"
+    fi
 fi
 
 # add reasonable default modules, works only after kernel is properly installed
