Disable fsck for btrfs as well.
The fsck.btrfs is not included by default, therefor fsck fails on first
boot. It's part of btrfs-tools (available for both wheezy and jessie), so if
that package is included, fsck.btrfs does work and /etc/fstab can be
configured accordingly.
But until that package is included by default, we'll disable fsck for
btrfs as well.

diff --git a/scripts/etc/init.d/rcS b/scripts/etc/init.d/rcS
--- a/scripts/etc/init.d/rcS
+++ b/scripts/etc/init.d/rcS
@@ -383,6 +383,8 @@ echo -n root:$rootpw | chroot /rootfs /usr/sbin/chpasswd || fail
 echo "$bootpartition /boot vfat defaults 0 2" > /rootfs/etc/fstab || fail
 if [ "$rootfstype" = "f2fs" ]; then
 	echo "$rootpartition / $rootfstype $rootfs_mount_options 0 0" >> /rootfs/etc/fstab || fail
+elif [ "$rootfstype" = "btrfs" ]; then
+	echo "$rootpartition / $rootfstype $rootfs_mount_options 0 0" >> /rootfs/etc/fstab || fail
 else
 	echo "$rootpartition / $rootfstype $rootfs_mount_options 0 1" >> /rootfs/etc/fstab || fail
 fi
