Added kernel upgrade handler script
rcS creates a script that automagically gets called when the kernel is
upgraded (or an older kernel package gets installed), and copies both
the new vmlinux-* and the new initrd.img-* to the appropriate files.
after this the content of config.txt is changed as well to reflect the
change

this is **not** done during installation, so the content of config.txt
will change when the first kernel update is performed

diff --git a/scripts/etc/init.d/rcS b/scripts/etc/init.d/rcS
--- a/scripts/etc/init.d/rcS
+++ b/scripts/etc/init.d/rcS
@@ -537,6 +537,33 @@ echo ""
 # there is no hw clock on rpi
 echo "HWCLOCKACCESS=no" >> /rootfs/etc/default/hwclock || fail
 
+# create the kernel upgrade handler script
+echo -n "Creating kernel upgrade handler script... "
+(
+cat <<-EOScript
+    #!/bin/sh -e
+
+    version="$1"
+    boot_dir=$(dirname "$2")
+
+    config_file="$boot_dir/config.txt"
+
+    cp --remove-destination "$boot_dir/vmlinuz-$version" "$boot_dir/kernel.img"
+    cp --remove-destination "$boot_dir/initrd.img-$version" "$boot_dir/initrd.img"
+
+    (
+    cat <<-EOConfig
+        kernel=kernel.img
+        initramfs initrd.img followkernel
+    EOConfig
+    ) > $config_file    
+EOScript
+) > /rootfs/etc/kernel/postinst.d/raspbian-ua-netinst
+if [ $? -eq 0 ]; then
+    echo "OK"
+else
+    echo "FAILED !"
+fi
 
 # remove cdebootstrap-helper-rc.d which prevents rc.d scripts from running
 echo -n "Removing cdebootstrap-helper-rc.d... " 
