Added apt_keys option
the option allows the user to set a list of URLs to GPG keys, which are
downloaded and installed into the system.
this way additional packages (from $packages) can be installed even if
GPG keys need to be used to access the package repositories

diff --git a/scripts/etc/init.d/rcS b/scripts/etc/init.d/rcS
--- a/scripts/etc/init.d/rcS
+++ b/scripts/etc/init.d/rcS
@@ -6,6 +6,7 @@ LOGFILE=/tmp/raspbian-ua-netinst.log
 preset=server
 packages=
 apt_sources=
+apt_keys=
 mirror=http://mirrordirector.raspbian.org/raspbian/
 release=wheezy
 hostname=pi
@@ -338,6 +339,7 @@ echo "Installer configuration:"
 echo "  preset = $preset"
 echo "  packages = $packages"
 echo "  apt_sources = $apt_sources"
+echo "  apt_keys = $apt_keys"
 echo "  mirror = $mirror"
 echo "  release = $release"
 echo "  hostname = $hostname"
@@ -580,6 +582,22 @@ echo -n "Removing cdebootstrap-helper-rc.d... "
 chroot /rootfs /usr/bin/dpkg -r cdebootstrap-helper-rc.d &>/dev/null || fail
 echo "OK"
 
+# add GPG keys to installed system
+if [ "${apt_keys}" != "" ]; then
+    echo -n "Installing GPG keys... "
+    failed=no
+    for URL in ${apt_keys}; do
+        wget -qO - ${URL} | chroot /rootfs /usr/bin/apt-key add - &> /dev/null
+        if [ $? -ne 0 ]; then
+            echo "  Failed adding ${URL}"
+            failed=yes
+        fi
+    done
+    if [ "${failed}" == "no" ]; then
+        echo "OK"
+    fi
+fi
+
 # add firmware to default apt sources
 echo -n "Configuring apt... "
 echo "deb http://mirrordirector.raspbian.org/raspbian $release main firmware" > /rootfs/etc/apt/sources.list
@@ -593,6 +611,7 @@ if [ "${apt_sources}" != "" ]; then
     # just in case
     mkdir -p /rootfs/etc/apt/sources.list.d
     echo "${apt_sources}" > /rootfs/etc/apt/sources.list.d/raspbian-ua-netinst.list
+    echo "OK"
 fi
 
 # add preferences file to install libraspberrypi-bin and friends (for vcgencmd) from the raspbian archives
